//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IApiClient {

    /**
     * @return OK
     */
    anonymous(signal?: AbortSignal): Promise<void>;

    /**
     * @return OK
     */
    classAll(signal?: AbortSignal): Promise<ClassResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    classPOST(body?: ClassCreate | undefined, signal?: AbortSignal): Promise<ClassResponse>;

    /**
     * @return OK
     */
    classGET(id: string, signal?: AbortSignal): Promise<ClassResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    classPUT(id: string, body?: ClassUpdate | undefined, signal?: AbortSignal): Promise<ClassResponse>;

    /**
     * @return OK
     */
    classDELETE(id: string, signal?: AbortSignal): Promise<void>;

    /**
     * @return OK
     */
    dnd5e(signal?: AbortSignal): Promise<void>;

    /**
     * @return OK
     */
    schoolAll(signal?: AbortSignal): Promise<SchoolResponse[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    schoolPOST(body?: SchoolCreate | undefined, signal?: AbortSignal): Promise<SchoolResponse>;

    /**
     * @return OK
     */
    schoolGET(id: string, signal?: AbortSignal): Promise<SchoolResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    schoolPUT(id: string, body?: SchoolUpdate | undefined, signal?: AbortSignal): Promise<SchoolResponse>;

    /**
     * @return OK
     */
    schoolDELETE(id: string, signal?: AbortSignal): Promise<void>;

    /**
     * @param q (optional) 
     * @param level (optional) 
     * @param classId (optional) 
     * @param page (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    spellGET(q?: string | undefined, level?: number | undefined, classId?: string | undefined, page?: number | undefined, pageSize?: number | undefined, signal?: AbortSignal): Promise<SpellResponseDtoPagedResult>;

    /**
     * @param body (optional) 
     * @return OK
     */
    spellPOST(body?: SpellCreateDto | undefined, signal?: AbortSignal): Promise<SpellResponseDto>;

    /**
     * @return OK
     */
    spellGET2(id: string, signal?: AbortSignal): Promise<SpellResponseDto>;

    /**
     * @param body (optional) 
     * @return OK
     */
    spellPUT(id: string, body?: SpellUpdateDto | undefined, signal?: AbortSignal): Promise<SpellResponseDto>;

    /**
     * @return OK
     */
    spellDELETE(id: string, signal?: AbortSignal): Promise<void>;
}

export class ApiClient implements IApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    anonymous(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAnonymous(_response);
        });
    }

    protected processAnonymous(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    classAll(signal?: AbortSignal): Promise<ClassResponse[]> {
        let url_ = this.baseUrl + "/api/Class";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processClassAll(_response);
        });
    }

    protected processClassAll(response: Response): Promise<ClassResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ClassResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClassResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    classPOST(body?: ClassCreate | undefined, signal?: AbortSignal): Promise<ClassResponse> {
        let url_ = this.baseUrl + "/api/Class";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processClassPOST(_response);
        });
    }

    protected processClassPOST(response: Response): Promise<ClassResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ClassResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClassResponse>(null as any);
    }

    /**
     * @return OK
     */
    classGET(id: string, signal?: AbortSignal): Promise<ClassResponse> {
        let url_ = this.baseUrl + "/api/Class/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processClassGET(_response);
        });
    }

    protected processClassGET(response: Response): Promise<ClassResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ClassResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClassResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    classPUT(id: string, body?: ClassUpdate | undefined, signal?: AbortSignal): Promise<ClassResponse> {
        let url_ = this.baseUrl + "/api/Class/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processClassPUT(_response);
        });
    }

    protected processClassPUT(response: Response): Promise<ClassResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ClassResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClassResponse>(null as any);
    }

    /**
     * @return OK
     */
    classDELETE(id: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/Class/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processClassDELETE(_response);
        });
    }

    protected processClassDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    dnd5e(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/Import/dnd5e";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDnd5e(_response);
        });
    }

    protected processDnd5e(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    schoolAll(signal?: AbortSignal): Promise<SchoolResponse[]> {
        let url_ = this.baseUrl + "/api/School";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSchoolAll(_response);
        });
    }

    protected processSchoolAll(response: Response): Promise<SchoolResponse[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SchoolResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SchoolResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    schoolPOST(body?: SchoolCreate | undefined, signal?: AbortSignal): Promise<SchoolResponse> {
        let url_ = this.baseUrl + "/api/School";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSchoolPOST(_response);
        });
    }

    protected processSchoolPOST(response: Response): Promise<SchoolResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SchoolResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SchoolResponse>(null as any);
    }

    /**
     * @return OK
     */
    schoolGET(id: string, signal?: AbortSignal): Promise<SchoolResponse> {
        let url_ = this.baseUrl + "/api/School/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSchoolGET(_response);
        });
    }

    protected processSchoolGET(response: Response): Promise<SchoolResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SchoolResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SchoolResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    schoolPUT(id: string, body?: SchoolUpdate | undefined, signal?: AbortSignal): Promise<SchoolResponse> {
        let url_ = this.baseUrl + "/api/School/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSchoolPUT(_response);
        });
    }

    protected processSchoolPUT(response: Response): Promise<SchoolResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SchoolResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SchoolResponse>(null as any);
    }

    /**
     * @return OK
     */
    schoolDELETE(id: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/School/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSchoolDELETE(_response);
        });
    }

    protected processSchoolDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param q (optional) 
     * @param level (optional) 
     * @param classId (optional) 
     * @param page (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    spellGET(q?: string | undefined, level?: number | undefined, classId?: string | undefined, page?: number | undefined, pageSize?: number | undefined, signal?: AbortSignal): Promise<SpellResponseDtoPagedResult> {
        let url_ = this.baseUrl + "/api/Spell?";
        if (q === null)
            throw new globalThis.Error("The parameter 'q' cannot be null.");
        else if (q !== undefined)
            url_ += "q=" + encodeURIComponent("" + q) + "&";
        if (level === null)
            throw new globalThis.Error("The parameter 'level' cannot be null.");
        else if (level !== undefined)
            url_ += "level=" + encodeURIComponent("" + level) + "&";
        if (classId === null)
            throw new globalThis.Error("The parameter 'classId' cannot be null.");
        else if (classId !== undefined)
            url_ += "classId=" + encodeURIComponent("" + classId) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSpellGET(_response);
        });
    }

    protected processSpellGET(response: Response): Promise<SpellResponseDtoPagedResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpellResponseDtoPagedResult.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpellResponseDtoPagedResult>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    spellPOST(body?: SpellCreateDto | undefined, signal?: AbortSignal): Promise<SpellResponseDto> {
        let url_ = this.baseUrl + "/api/Spell";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSpellPOST(_response);
        });
    }

    protected processSpellPOST(response: Response): Promise<SpellResponseDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpellResponseDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpellResponseDto>(null as any);
    }

    /**
     * @return OK
     */
    spellGET2(id: string, signal?: AbortSignal): Promise<SpellResponseDto> {
        let url_ = this.baseUrl + "/api/Spell/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSpellGET2(_response);
        });
    }

    protected processSpellGET2(response: Response): Promise<SpellResponseDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpellResponseDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpellResponseDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    spellPUT(id: string, body?: SpellUpdateDto | undefined, signal?: AbortSignal): Promise<SpellResponseDto> {
        let url_ = this.baseUrl + "/api/Spell/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSpellPUT(_response);
        });
    }

    protected processSpellPUT(response: Response): Promise<SpellResponseDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpellResponseDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpellResponseDto>(null as any);
    }

    /**
     * @return OK
     */
    spellDELETE(id: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/Spell/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSpellDELETE(_response);
        });
    }

    protected processSpellDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class ClassCreate implements IClassCreate {
    id?: string | undefined;
    name?: string | undefined;

    constructor(data?: IClassCreate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): ClassCreate {
        data = typeof data === 'object' ? data : {};
        let result = new ClassCreate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface IClassCreate {
    id?: string | undefined;
    name?: string | undefined;
}

export class ClassResponse implements IClassResponse {
    id?: string | undefined;
    name?: string | undefined;

    constructor(data?: IClassResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): ClassResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ClassResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface IClassResponse {
    id?: string | undefined;
    name?: string | undefined;
}

export class ClassUpdate implements IClassUpdate {
    name?: string | undefined;

    constructor(data?: IClassUpdate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): ClassUpdate {
        data = typeof data === 'object' ? data : {};
        let result = new ClassUpdate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        return data;
    }
}

export interface IClassUpdate {
    name?: string | undefined;
}

export class SchoolCreate implements ISchoolCreate {
    id?: string | undefined;
    name?: string | undefined;

    constructor(data?: ISchoolCreate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): SchoolCreate {
        data = typeof data === 'object' ? data : {};
        let result = new SchoolCreate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface ISchoolCreate {
    id?: string | undefined;
    name?: string | undefined;
}

export class SchoolResponse implements ISchoolResponse {
    id?: string | undefined;
    name?: string | undefined;

    constructor(data?: ISchoolResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): SchoolResponse {
        data = typeof data === 'object' ? data : {};
        let result = new SchoolResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface ISchoolResponse {
    id?: string | undefined;
    name?: string | undefined;
}

export class SchoolUpdate implements ISchoolUpdate {
    name?: string | undefined;

    constructor(data?: ISchoolUpdate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): SchoolUpdate {
        data = typeof data === 'object' ? data : {};
        let result = new SchoolUpdate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        return data;
    }
}

export interface ISchoolUpdate {
    name?: string | undefined;
}

export class SpellCreateDto implements ISpellCreateDto {
    id?: string | undefined;
    name!: string;
    level?: number;
    schoolId?: string | undefined;
    castingTime?: string | undefined;
    range?: string | undefined;
    components?: string | undefined;
    duration?: string | undefined;
    concentration?: boolean;
    ritual?: boolean;
    description?: string | undefined;
    higherLevel?: string | undefined;
    classIds?: string[] | undefined;

    constructor(data?: ISpellCreateDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.level = _data["level"];
            this.schoolId = _data["schoolId"];
            this.castingTime = _data["castingTime"];
            this.range = _data["range"];
            this.components = _data["components"];
            this.duration = _data["duration"];
            this.concentration = _data["concentration"];
            this.ritual = _data["ritual"];
            this.description = _data["description"];
            this.higherLevel = _data["higherLevel"];
            if (Array.isArray(_data["classIds"])) {
                this.classIds = [] as any;
                for (let item of _data["classIds"])
                    this.classIds!.push(item);
            }
        }
    }

    static fromJS(data: any): SpellCreateDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpellCreateDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["level"] = this.level;
        data["schoolId"] = this.schoolId;
        data["castingTime"] = this.castingTime;
        data["range"] = this.range;
        data["components"] = this.components;
        data["duration"] = this.duration;
        data["concentration"] = this.concentration;
        data["ritual"] = this.ritual;
        data["description"] = this.description;
        data["higherLevel"] = this.higherLevel;
        if (Array.isArray(this.classIds)) {
            data["classIds"] = [];
            for (let item of this.classIds)
                data["classIds"].push(item);
        }
        return data;
    }
}

export interface ISpellCreateDto {
    id?: string | undefined;
    name: string;
    level?: number;
    schoolId?: string | undefined;
    castingTime?: string | undefined;
    range?: string | undefined;
    components?: string | undefined;
    duration?: string | undefined;
    concentration?: boolean;
    ritual?: boolean;
    description?: string | undefined;
    higherLevel?: string | undefined;
    classIds?: string[] | undefined;
}

export class SpellResponseDto implements ISpellResponseDto {
    id?: string | undefined;
    name?: string | undefined;
    level?: number;
    schoolId?: string | undefined;
    castingTime?: string | undefined;
    range?: string | undefined;
    components?: string | undefined;
    duration?: string | undefined;
    concentration?: boolean;
    ritual?: boolean;
    description?: string | undefined;
    higherLevel?: string | undefined;

    constructor(data?: ISpellResponseDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.level = _data["level"];
            this.schoolId = _data["schoolId"];
            this.castingTime = _data["castingTime"];
            this.range = _data["range"];
            this.components = _data["components"];
            this.duration = _data["duration"];
            this.concentration = _data["concentration"];
            this.ritual = _data["ritual"];
            this.description = _data["description"];
            this.higherLevel = _data["higherLevel"];
        }
    }

    static fromJS(data: any): SpellResponseDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpellResponseDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["level"] = this.level;
        data["schoolId"] = this.schoolId;
        data["castingTime"] = this.castingTime;
        data["range"] = this.range;
        data["components"] = this.components;
        data["duration"] = this.duration;
        data["concentration"] = this.concentration;
        data["ritual"] = this.ritual;
        data["description"] = this.description;
        data["higherLevel"] = this.higherLevel;
        return data;
    }
}

export interface ISpellResponseDto {
    id?: string | undefined;
    name?: string | undefined;
    level?: number;
    schoolId?: string | undefined;
    castingTime?: string | undefined;
    range?: string | undefined;
    components?: string | undefined;
    duration?: string | undefined;
    concentration?: boolean;
    ritual?: boolean;
    description?: string | undefined;
    higherLevel?: string | undefined;
}

export class SpellResponseDtoPagedResult implements ISpellResponseDtoPagedResult {
    items?: SpellResponseDto[] | undefined;
    total?: number;
    page?: number;
    pageSize?: number;

    constructor(data?: ISpellResponseDtoPagedResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(SpellResponseDto.fromJS(item));
            }
            this.total = _data["total"];
            this.page = _data["page"];
            this.pageSize = _data["pageSize"];
        }
    }

    static fromJS(data: any): SpellResponseDtoPagedResult {
        data = typeof data === 'object' ? data : {};
        let result = new SpellResponseDtoPagedResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        data["total"] = this.total;
        data["page"] = this.page;
        data["pageSize"] = this.pageSize;
        return data;
    }
}

export interface ISpellResponseDtoPagedResult {
    items?: SpellResponseDto[] | undefined;
    total?: number;
    page?: number;
    pageSize?: number;
}

export class SpellUpdateDto implements ISpellUpdateDto {
    name!: string;
    level?: number;
    schoolId?: string | undefined;
    castingTime?: string | undefined;
    range?: string | undefined;
    components?: string | undefined;
    duration?: string | undefined;
    concentration?: boolean;
    ritual?: boolean;
    description?: string | undefined;
    higherLevel?: string | undefined;
    classIds?: string[] | undefined;

    constructor(data?: ISpellUpdateDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.level = _data["level"];
            this.schoolId = _data["schoolId"];
            this.castingTime = _data["castingTime"];
            this.range = _data["range"];
            this.components = _data["components"];
            this.duration = _data["duration"];
            this.concentration = _data["concentration"];
            this.ritual = _data["ritual"];
            this.description = _data["description"];
            this.higherLevel = _data["higherLevel"];
            if (Array.isArray(_data["classIds"])) {
                this.classIds = [] as any;
                for (let item of _data["classIds"])
                    this.classIds!.push(item);
            }
        }
    }

    static fromJS(data: any): SpellUpdateDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpellUpdateDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["level"] = this.level;
        data["schoolId"] = this.schoolId;
        data["castingTime"] = this.castingTime;
        data["range"] = this.range;
        data["components"] = this.components;
        data["duration"] = this.duration;
        data["concentration"] = this.concentration;
        data["ritual"] = this.ritual;
        data["description"] = this.description;
        data["higherLevel"] = this.higherLevel;
        if (Array.isArray(this.classIds)) {
            data["classIds"] = [];
            for (let item of this.classIds)
                data["classIds"].push(item);
        }
        return data;
    }
}

export interface ISpellUpdateDto {
    name: string;
    level?: number;
    schoolId?: string | undefined;
    castingTime?: string | undefined;
    range?: string | undefined;
    components?: string | undefined;
    duration?: string | undefined;
    concentration?: boolean;
    ritual?: boolean;
    description?: string | undefined;
    higherLevel?: string | undefined;
    classIds?: string[] | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}