<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Xunit.DependencyInjection" Version="11.0.0" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.5.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
    </ItemGroup>

    <!-- vigtig: Tests afhænger af Api (som afhænger af DataAccess) -->
    <ItemGroup>
        <ProjectReference Include="..\Api\Api.csproj" />
    </ItemGroup>

</Project>

